# Takes in a pip requirements.txt file and converts it to a conda environment.yml file

PIP_REQUIREMENTS_LOCATION = "./requirements/deploy.txt"
OUTPUT_LOCATION = "./deployment_config/online_endpoint/conda_env.yml"


def main():
    # Load in the pip requirements
    with open(PIP_REQUIREMENTS_LOCATION, "r") as f:
        pip_requirements = f.readlines()

    output_conda_file = """
# Auto-generated conda environment file used for deployment.  This file is generated from the pip requirements.txt file by the script convert_pip_to_conda.py.
# Do not edit this file directly.  Instead, edit the pip requirements.txt file and run the script to generate a new conda environment file.

name: project_environment
dependencies:
  - python=3.9.11

  - pip:\n"""
    for line in pip_requirements:
        if line.startswith("#"):
            continue
        if line.startswith("-r"):
            output_conda_file += f"    -r {line[2:]}"
        else:
            output_conda_file += f"    - {line}"

    output_conda_file += """
channels:
  - anaconda
  - conda-forge
    """

    # Write out the conda environment.yml file
    with open(OUTPUT_LOCATION, "w") as f:
        f.write(output_conda_file)


if __name__ == "__main__":
    main()
