$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: prime-predictions-batch
endpoint_name: prime-predictions-batch-endpoint
model:
  # this is a dummy parameter
  path: ../code/deploy/datascience_prime_predictions/pickled_models/
code_configuration:
  code: ../code/deploy
  scoring_script: score_batch_endpoint.py
environment:
  conda_file: ../code/deploy/environment.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
compute: azureml:batch-inference-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 3000
error_threshold: -1
logging_level: info
